### ISSUE TITLE
Support for Lark-style EBNF

### ISSUE THREAD

**Issue by ThatXliner** [Alhadis/language-grammars#4]
[Lark](lark-parser.readthedocs.io) is a parsing library for python. It's flavored EBNF files (`.lark`) needs syntax highlighting. The only difference between lark EBNF (which I'll refer to as LEBNF) and EBNF is that LEBNF's comments are js-style, without multi-line comment support, brackets denote optional groups, a `?` and/or `!` are operators that _may_ appear before the definition of a rule or `TERMINAL`, priority, denoted by `TERMINAL.number`, is a thing, and it has `%import`, `%ignore`, and `%declare` statements.

Detailed grammar reference can be found [here](https://lark-parser.readthedocs.io/en/latest/grammar.html)

Would you modify `EBNF.cson`, and turn it to `LEBNF.cson`, please? I have no idea on how to write an atom grammar (I find it poorly documented on atom.io)

**Comment by Alhadis** [comment]
I'll see what I can do. 👍 Rather than modify EBNF's grammar, though, it'll be better to add a dedicated grammar for LEBNF instead. Lark's format is [well-defined](https://lark-parser.readthedocs.io/en/latest/grammar.html#general-syntax-and-notes) and uses a non-conflicting file extension, whereas `ebnf.cson` attempts to accommodate *every* syntax variation that might be encountered in `.ebnf` files (which rarely conform to ISO/IEC 14977).

> I have no idea on how to write an atom grammar (I find it poorly documented on atom.io)

It's actually [TextMate's grammar format](https://macromates.com/manual/en/language_grammars), adopted by Atom/GitHub, VSCode, and Sublime Text. Each have different requirements on file format: Atom uses [CSON](https://github.com/bevry/cson)/JSON, VSCode and TextMate use [XML property lists](https://macromates.com/manual/en/appendix#property-list-format), and Sublime uses [YAML](https://www.sublimetext.com/docs/3/syntax.html). Regardless of their representation, all TextMate-compatible grammars are structurally similar, and the ones you'll encounter are often converted from a TextMate bundle (except mine… I proudly pen them all from scratch).

Other than [TextMate's grammar reference](https://macromates.com/manual/en/language_grammars#naming_conventions), the only other reliable source of info (that I know of) is [this blog post](http://www.apeth.com/nonblog/stories/textmatebundle.html). It covers several critical (but undocumented) details of writing a TMCG, and discusses the hacks necessary to work around TextMate's notorious lack of multiline pattern support.

**Comment by Alhadis** [comment]
Righto, all done! This covers everything in both [the docs](https://lark-parser.readthedocs.io/en/latest/grammar.html#general-syntax-and-notes) and [Lark's own grammar definition](https://github.com/lark-parser/lark/blob/082e0f3de763bd3883e556390813a89fd139c44e/examples/lark.lark). Here's a preview:

<img src="https://user-images.githubusercontent.com/2346707/95926361-ceadf900-0e07-11eb-8bec-ff64da1e1ed3.png" alt="Figure 1" />

**Comment by Alhadis** [comment]
I've also submitted a PR to have Lark grammars supported/highlighted on GitHub. See github/linguist#5049.
